### ISSUE TITLE
which command bug in linux environment

### ISSUE THREAD

**Issue by tuladhar-p** [RohitRox/cf-tools#1]
@RohitRox Linux environment doesn't have `which` silent flag (-s), thus following error is displayed when running `cf-tools install-tools`

```
/usr/bin/which: invalid option -- 's'
/usr/bin/aws
/usr/bin/which: invalid option -- 's'
/usr/bin/jq
```

Reference:
- https://linux.die.net/man/1/which

**Comment by RohitRox** [comment]
Fixed at bc931f8
